debug: true
language: ruby
cache: bundler
rvm:
  - 1.9.3-p547
services:
  - postgresql
  - mongodb
  - redis-server
  - memcached
before_install:
  - gem update --system 1.8.29
  - gem --version
script:
  - CODECLIMATE_REPO_TOKEN=5389167df5c64410b9561acec862f703b86eb45d1454d356878ce6dd8bcbb8a3 bundle exec rake
