language: ruby
rvm:
- 1.8.7
- 1.9.3
- 2.1.2
- 2.2.0
- ruby-head
script:
- bundle exec rspec
- bundle exec rake
before_install:
- openssl aes-256-cbc -K $encrypted_7fc7f2c03573_key -iv $encrypted_7fc7f2c03573_iv
  -in user.yml.enc -out user.yml -d
