module ZerigoDNS
  #@attr [String] api_key The Api key generated by Zerigo DNS
  #@attr [String] user Your e-mail address
  #@attr [Boolean] secure Whether to use HTTPS
  class Config
    attr_accessor :api_key, :user, :secure, :site
    
    def secure?
      !!secure
    end
  end
end
