module ZerigoDNS
  #@attr [String] api_key The Api key generated by Zerigo DNS
  #@attr [String] user Your e-mail address
  #@attr [Boolean] secure Whether to use HTTPS
  class Config
    
    BASE_ATTRIBUTES = %w(api_key site secure user password)
      BASE_ATTRIBUTES.each do |attr|
        define_method attr do
          ZerigoDNS::Base.send(attr)
        end
        
        define_method "#{attr}=" do |val|
          ZerigoDNS::Base.send("#{attr}=", val)
        end
      end
  end
end
